//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLKI.Programme.RaMaDe.src.Forms {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class frmMain_Stringtable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal frmMain_Stringtable() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLKI.Programme.RaMaDe.src.Forms.frmMain.Stringtable", typeof(frmMain_Stringtable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen abgeschlossen.
        ///
        ///{0} Dateien gelöscht.
        ///{1} Fehler beim löschen
        ///
        ///Möchten Sie das Programm jetzt beenden? ähnelt.
        /// </summary>
        internal static string _0c0002m {
            get {
                return ResourceManager.GetString("0c0002m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Dateien löschen? ähnelt.
        /// </summary>
        internal static string _0x0001c {
            get {
                return ResourceManager.GetString("0x0001c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Dateien zum Löschen gefunden. Möchte Sie diese jetzt löschen?
        ///
        ///ACHTUNG: Die Dateien werden gelöscht und nicht in den Papierkorb verschoben. Dieser Vorgang kann nicht rückgängig gemacht werden. ähnelt.
        /// </summary>
        internal static string _0x0001m {
            get {
                return ResourceManager.GetString("0x0001m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Dateien löschen. ähnelt.
        /// </summary>
        internal static string _0x0002c {
            get {
                return ResourceManager.GetString("0x0002c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner nicht gefunden. ähnelt.
        /// </summary>
        internal static string _0x0003c {
            get {
                return ResourceManager.GetString("0x0003c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der angegebene Pfad konnte nicht gefunden werden. ähnelt.
        /// </summary>
        internal static string _0x0003m {
            get {
                return ResourceManager.GetString("0x0003m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateien löschen. ähnelt.
        /// </summary>
        internal static string _0x0004c {
            get {
                return ResourceManager.GetString("0x0004c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Dateien zum Löschen gefunden.
        ///
        ///Möchten Sie das Programm jetzt beenden? ähnelt.
        /// </summary>
        internal static string _0x0004m {
            get {
                return ResourceManager.GetString("0x0004m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner mit Bildern auswählen ähnelt.
        /// </summary>
        internal static string _0x0005 {
            get {
                return ResourceManager.GetString("0x0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateien zum Löschen suchen ähnelt.
        /// </summary>
        internal static string _0x0006c {
            get {
                return ResourceManager.GetString("0x0006c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Suchen von Dateien zum Löschen ist ein Fehler aufgetreten.
        ///
        ///{0} ähnelt.
        /// </summary>
        internal static string _0x0006m {
            get {
                return ResourceManager.GetString("0x0006m", resourceCulture);
            }
        }
    }
}
