//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLKI.Programme.RaMaDe.src.Forms {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class frmMain_Mres {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal frmMain_Mres() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLKI.Programme.RaMaDe.src.Forms.frmMain_Mres", typeof(frmMain_Mres).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Dateien löschen? ähnelt.
        /// </summary>
        internal static string btnDeleteRawFileClick__DeleteFiles_Caption {
            get {
                return ResourceManager.GetString("btnDeleteRawFileClick__DeleteFiles_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Datteien zum löschen gefunden. Möchte Sie diese jetzt löschen?
        ///
        ///ACHTUNG: Die Dateien werden gelöscht und nicht in den Papierkorb verschoben. Dieser Vorgang kann nicht rückgängig gemacht werden. ähnelt.
        /// </summary>
        internal static string btnDeleteRawFileClick__DeleteFiles_Message {
            get {
                return ResourceManager.GetString("btnDeleteRawFileClick__DeleteFiles_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Dateien löschen. ähnelt.
        /// </summary>
        internal static string btnDeleteRawFileClick__Finish_Caption {
            get {
                return ResourceManager.GetString("btnDeleteRawFileClick__Finish_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen abgeschlossen.
        ///
        ///{0} Dateien gelöscht.
        ///{1} Fehler beim löschen
        ///
        ///Möchen Sie das Programm jetzt beenden? ähnelt.
        /// </summary>
        internal static string btnDeleteRawFileClick__Finish_Message {
            get {
                return ResourceManager.GetString("btnDeleteRawFileClick__Finish_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner nicht gefunden. ähnelt.
        /// </summary>
        internal static string btnDeleteRawFileClick__NoDirectroy_Caption {
            get {
                return ResourceManager.GetString("btnDeleteRawFileClick__NoDirectroy_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der angegebene Pfad konnte nicht gefunden werden. ähnelt.
        /// </summary>
        internal static string btnDeleteRawFileClick__NoDirectroy_Message {
            get {
                return ResourceManager.GetString("btnDeleteRawFileClick__NoDirectroy_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateien löschen. ähnelt.
        /// </summary>
        internal static string btnDeleteRawFileClick__NoFiles_Caption {
            get {
                return ResourceManager.GetString("btnDeleteRawFileClick__NoFiles_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Dateien zum löschen gefunden.
        ///
        ///Möchen Sie das Programm jetzt beenden? ähnelt.
        /// </summary>
        internal static string btnDeleteRawFileClick__NoFiles_Message {
            get {
                return ResourceManager.GetString("btnDeleteRawFileClick__NoFiles_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner mit Bildern auswählen ähnelt.
        /// </summary>
        internal static string btnDirectoryClick__FolderBrowser_Description {
            get {
                return ResourceManager.GetString("btnDirectoryClick__FolderBrowser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateien zum löschen suchen ähnelt.
        /// </summary>
        internal static string btnDirectoryClick__SearchException_Caption {
            get {
                return ResourceManager.GetString("btnDirectoryClick__SearchException_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Suchen von Dateien zum löschen ist ein Fehler aufgetreten.
        ///
        ///{0} ähnelt.
        /// </summary>
        internal static string btnDirectoryClick__SearchException_Message {
            get {
                return ResourceManager.GetString("btnDirectoryClick__SearchException_Message", resourceCulture);
            }
        }
    }
}
